
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;
	private global::Gtk.Label lblID;
	private global::Gtk.Label lblNombre;
	private global::Gtk.Label lblAnio;
	private global::Gtk.Button btnMostar;
	private global::Gtk.Label lblOpciones;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblID = new global::Gtk.Label ();
		this.lblID.Name = "lblID";
		this.lblID.LabelProp = global::Mono.Unix.Catalog.GetString ("ID");
		this.fixed1.Add (this.lblID);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lblID]));
		w1.X = 26;
		w1.Y = 23;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblNombre = new global::Gtk.Label ();
		this.lblNombre.Name = "lblNombre";
		this.lblNombre.LabelProp = global::Mono.Unix.Catalog.GetString ("NOMBRE");
		this.fixed1.Add (this.lblNombre);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lblNombre]));
		w2.X = 127;
		w2.Y = 23;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblAnio = new global::Gtk.Label ();
		this.lblAnio.Name = "lblAnio";
		this.lblAnio.LabelProp = global::Mono.Unix.Catalog.GetString ("AÑO");
		this.fixed1.Add (this.lblAnio);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lblAnio]));
		w3.X = 234;
		w3.Y = 24;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnMostar = new global::Gtk.Button ();
		this.btnMostar.CanFocus = true;
		this.btnMostar.Name = "btnMostar";
		this.btnMostar.UseUnderline = true;
		this.btnMostar.Label = global::Mono.Unix.Catalog.GetString ("MOSTRAR");
		this.fixed1.Add (this.btnMostar);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnMostar]));
		w4.X = 419;
		w4.Y = 66;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblOpciones = new global::Gtk.Label ();
		this.lblOpciones.Name = "lblOpciones";
		this.lblOpciones.LabelProp = global::Mono.Unix.Catalog.GetString ("OPCIONES");
		this.fixed1.Add (this.lblOpciones);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lblOpciones]));
		w5.X = 423;
		w5.Y = 25;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 600;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.btnMostar.Clicked += new global::System.EventHandler (this.OnBtnMostarClicked);
	}
}
